name: My Workflow 2

on:
    push:
        branches:
        - main
    # pull_request:
    #     branches:
    #     - main

jobs:
    job1:
        runs-on: windows-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Run a script
          run: echo "Hello, world!"
    
    job2:
        runs-on: windows-latest
        needs: job1
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Run another script
          run: echo "Hello, again!"
